package dev.hylfrd.farmhelper.control.inventory;

/** Closed fail-closed terminal and rejection reasons for inventory work. */
public enum InventoryCancelReason {
    REQUESTED,
    TIMEOUT,
    OWNER_CONFLICT,
    STALE_TOKEN,
    SCREEN_CLOSED,
    SCREEN_CHANGED,
    SCREEN_IDENTITY_MISMATCH,
    SCREEN_TYPE_MISMATCH,
    SCREEN_TITLE_MISMATCH,
    SCREEN_SLOT_COUNT_MISMATCH,
    SCREEN_SENTINEL_MISSING,
    REVISION_CHANGED,
    SLOT_NOT_FOUND,
    SLOT_OUT_OF_BOUNDS,
    SLOT_CHANGED,
    SLOT_INACTIVE,
    PICKUP_DENIED,
    ITEM_CHANGED,
    COUNT_CHANGED,
    CURSOR_CHANGED,
    CLOSED_BY_OPERATION,
    ADAPTER_EXCEPTION,
    VERIFIER_EXCEPTION,
    CALLBACK_EXCEPTION,
    DIAGNOSTIC_EXCEPTION
}
