package dev.hylfrd.farmhelper.feature.reconnect;

/** Typed explanation for a reconnect decision. */
public enum ReconnectReason {
    IDLE,
    STARTED,
    ALREADY_RUNNING,
    DELAY_PENDING,
    INITIAL_DISCONNECT_PENDING,
    CONNECTION_UNKNOWN,
    CONNECT_ATTEMPTED,
    CONNECTION_ESTABLISHED,
    CONNECTION_LOST,
    GAME_STATE_NOT_FRESH,
    GAME_STATE_UNKNOWN,
    GAME_STATE_CONTRADICTORY,
    GAME_STATE_TRANSITIONING,
    LOBBY_OBSERVED,
    LIMBO_OBSERVED,
    OUTSIDE_GARDEN,
    GARDEN_REACHED,
    MANUAL_CANCEL,
    STOP_REQUESTED,
    CANCEL_SCREEN_UNAVAILABLE,
    SINGLEPLAYER_UNSUPPORTED,
    PORT_FAILURE,
    DEADLINE_REACHED
}
